
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS-NB
 */
public class BiodataMhs extends javax.swing.JFrame {
    ResultSet result;
    Statement stetement;
    Connection koneksi;
    Boolean isEdit = false, isInsert = false;

    /**
     * Creates new form BiodataMhs
     */
    public BiodataMhs() throws SQLException {
        initComponents();
        doConnect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtNim = new javax.swing.JTextField();
        rbLaki = new javax.swing.JRadioButton();
        rbPerempuan = new javax.swing.JRadioButton();
        txtTanggal = new javax.swing.JTextField();
        txtAlamat = new javax.swing.JTextField();
        txtJur = new javax.swing.JTextField();
        txtFak = new javax.swing.JTextField();
        txtAngkatan = new javax.swing.JTextField();
        bnTambah = new javax.swing.JButton();
        bnSimpan = new javax.swing.JButton();
        bnHapus = new javax.swing.JButton();
        bnClose = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Biodata Mahasiswa");

        jLabel6.setText("Alamat");

        jLabel7.setText("Fakultas");

        jLabel8.setText("Jurusan");

        jLabel9.setText("Angkatan");

        jLabel2.setText("Tanggal Lahir");

        jLabel3.setText("Jenis Kelamin");

        jLabel4.setText("Nim");

        jLabel5.setText("Nama");

        rbLaki.setText("Laki-laki");

        rbPerempuan.setText("Perempuan");

        bnTambah.setText("Tambah");
        bnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnTambahActionPerformed(evt);
            }
        });

        bnSimpan.setText("Simpan");
        bnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnSimpanActionPerformed(evt);
            }
        });

        bnHapus.setText("Hapus");
        bnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnHapusActionPerformed(evt);
            }
        });

        bnClose.setText("Close");
        bnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnCloseActionPerformed(evt);
            }
        });

        jButton4.setText("<<");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText(">>");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNim, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbLaki)
                        .addGap(18, 18, 18)
                        .addComponent(rbPerempuan))
                    .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtJur, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFak, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAngkatan, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70))
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(bnTambah)
                .addGap(18, 18, 18)
                .addComponent(bnSimpan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bnHapus)
                .addGap(35, 35, 35)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bnClose)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtNim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbLaki)
                        .addComponent(rbPerempuan)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtFak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtJur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtAngkatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bnSimpan)
                        .addComponent(bnClose)
                        .addComponent(bnHapus)
                        .addComponent(jButton4)
                        .addComponent(jButton5))
                    .addComponent(bnTambah))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnTambahActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            final String username = "root";
            final String password = "";
            final Connection koneksi = DriverManager.getConnection(
            "jdbc:mysql://localhots:3306/latihan_db",username,password);
            
            PreparedStatement prepare = koneksi
                    .prepareStatement("INSERT INTO biodata_mhs"
                    +"(nim,nama,jenis_kelamin,tanggal_lahir,alamat,"
                    +"fakultas,jurusan,angkatan)"
                    +"VALUES(?,?,?,?,?,?,?,?,)"
                    );
                    prepare.setString(1,txtNim.getText());
                    prepare.setString(2,txtNama.getText());
                    String kelamin=null;
                    if(rbLaki.isSelected())
                        kelamin = "L";
                    else if(rbPerempuan.isSelected())
                        kelamin ="P";
                    prepare.setString(3,kelamin);
                    
                    SimpleDateFormat formater = new SimpleDateFormat("dd/MM/yyyy");
                    try{
                        java.util.Date date = formater.parse(txtTanggal.getText());
                        java.sql.Date sqlDate = new java.sql.Date(date.getTime());
                        prepare.setDate(4, (java.sql.Date) sqlDate);
                    } catch (ParseException e) {
                    }
                    prepare.setString(5, txtAlamat.getText());
                    prepare.setString(6, txtFak.getText());
                    prepare.setString(7, txtJur.getText());
                    prepare.setString(8, txtAngkatan.getText());
                    prepare.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Data berhasil ditambahkan.");
        } catch (final SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TambahData.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(TambahData.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(TambahData.class.getName()).log(Level.SEVERE, null, ex);
                    } 
    }//GEN-LAST:event_bnTambahActionPerformed

    private void bnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnSimpanActionPerformed
         try {
            
            result.updateString("Nim",txtNim.getText());
            result.updateString("Nama", txtNama.getText());
            
            String kelamin=null;
            if(rbLaki.isSelected())
                kelamin = "L";
            else if(rbPerempuan.isSelected())
                kelamin = "P";
            result.updateString("Jenis Kelamin", kelamin);
            
            SimpleDateFormat formater = new SimpleDateFormat("dd/MM/yyyy");
            
            try {
                java.util.Date date = formater.parse(txtTanggal.getText());
                java.sql.Date sqlDate = new java.sql.Date(date.getTime());
                result.updateDate("Tanggal Lahir",(java.sql.Date)sqlDate);
            } catch (ParseException ex) {
                }
            
            result.updateString("Alamat", txtAlamat.getText());
            result.updateString("Fakultas", txtFak.getText());
            result.updateString("Jurusan", txtJur.getText());
            result.updateString("Angkatan",txtAngkatan.getText());
            
            result.updateRow();
            
            JOptionPane.showMessageDialog(null,"Data berhasil diubah.");
            
        } catch (final SQLException ex) {
             try {
                 JOptionPane.showMessageDialog(null,ex.getMessage());
                 stetement = koneksi.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,
                         ResultSet.CONCUR_UPDATABLE);
                 String sql ="SELECT * FROM biodata_mhs";
                 result = stetement.executeQuery(sql);
             } catch (SQLException ex1) {
                 Logger.getLogger(BiodataMhs.class.getName()).log(Level.SEVERE, null, ex1);
             }
        }
         
    }//GEN-LAST:event_bnSimpanActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try {
                if (!result.isFirst()){
                    result.previous();
                    tampilData();
                }   } catch (SQLException ex) {
                Logger.getLogger(BiodataMhs.class.getName()).log(Level.SEVERE, null, ex);
            }
 
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try {
            if (!result.isLast()){
                result.next();
                tampilData();
            }
        } catch (SQLException ex) {
            Logger.getLogger(BiodataMhs.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void bnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnCloseActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_bnCloseActionPerformed

    private void bnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnHapusActionPerformed
        // TODO add your handling code here:
        
        try {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            String host = "jdbc:mysql://localhost:3306/latihan_db";
            String username = "root";
            String password = "";
            koneksi = DriverManager.getConnection(host, username, password);
            
           
            
             stetement = (Statement) koneksi.createStatement();
           String query = "DELETE FROM biodata_mhs WHERE Nim=?";
            PreparedStatement statement = (PreparedStatement) koneksi.prepareStatement(query);
            statement.setString(1,txtNim.getText());
            statement.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data berhasil dihapus.");
            tampilData();            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Terjadi error pada saat delete data");
        
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException ex) {
            Logger.getLogger(BiodataMhs.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
          
        }
    }//GEN-LAST:event_bnHapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BiodataMhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BiodataMhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BiodataMhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BiodataMhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new BiodataMhs().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(BiodataMhs.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnClose;
    private javax.swing.JButton bnHapus;
    private javax.swing.JButton bnSimpan;
    private javax.swing.JButton bnTambah;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton rbLaki;
    private javax.swing.JRadioButton rbPerempuan;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtAngkatan;
    private javax.swing.JTextField txtFak;
    private javax.swing.JTextField txtJur;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNim;
    private javax.swing.JTextField txtTanggal;
    // End of variables declaration//GEN-END:variables

    private void doConnect() throws SQLException {
        try {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            String host = "jdbc:mysql://localhost:3306/latihan_db";
            String username = "root";
            String password = "";
            koneksi = DriverManager.getConnection(host, username, password);
            
             stetement = (Statement) koneksi.createStatement();
            String sql = "SELECT*FROM biodata_mhs";
             result= stetement.executeQuery(sql);
             
            //pindahkan kursor pada record pertama
            result.first();
            tampilData();
            
        } catch (ClassNotFoundException | SQLException | InstantiationException 
                | IllegalAccessException ex) {
            Logger.getLogger(BiodataMhs.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void tampilData() throws SQLException {
        txtNim.setText(result.getString("Nim"));
        txtNama.setText(result.getString("Nama"));
        
        String kelamin = result.getString("Jenis Kelamin");
        switch(kelamin){
            case"L":
                rbLaki.setSelected(true);
                break;
            case"P":
                rbPerempuan.setSelected(true);
                break;
        }
        txtTanggal.setText(result.getString("Tanggal Lahir"));
        txtAlamat.setText(result.getString("Alamat"));
        txtFak.setText(result.getString("Fakultas"));
        txtJur.setText(result.getString("Jurusan"));
        txtAngkatan.setText(result.getString("Angkatan"));
    }

}
